CREATE TABLE IF NOT EXISTS aircraft (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tail_number VARCHAR(10) NOT NULL UNIQUE,
  model VARCHAR(50),
  location VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS personnel (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  rank VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  aircraft_id INT,
  personnel_id INT,
  task_id INT,
  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (aircraft_id) REFERENCES aircraft(id),
  FOREIGN KEY (personnel_id) REFERENCES personnel(id),
  FOREIGN KEY (task_id) REFERENCES task(id)
);